version: "3.9"

services:
  db:
      image: postgres:13
      restart: unless-stopped
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      environment:
        - POSTGRES_DB=ulloadb
        - POSTGRES_USER=ullouser
        - POSTGRES_PASSWORD=ullopass
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/UlloaWear
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=ulloadb
      - DB_USER=ullouser
      - DB_PASSWORD=ullopass
      - DB_HOST=db
    env_file: .env
  

volumes:
  postgres_data:
