# Generated by Django 4.0.10 on 2025-06-10 15:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_categoria_padre'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
