# Generated by Django 4.0.10 on 2025-06-10 16:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0003_categoria_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
