# Generated by Django 4.0.10 on 2025-06-07 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagenes',
            field=models.ImageField(upload_to='productos/'),
        ),
    ]
