# Generated by Django 4.0.10 on 2025-06-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_resena'),
    ]

    operations = [
        migrations.AddField(
            model_name='resena',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='reseñas/'),
        ),
    ]
