# Generated by Django 4.0.10 on 2025-06-10 15:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_resena_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
